id: sample-label-smoothing
pretrained: /home/ptthang/gaze_sample/runs/sample-label-smoothing-pe2d-023_02_15-16_36_10-resume-2023_02_18-13_02_27/last.pth
seed: 2612
amp: False
model:
    name: GazeBaseline
    args:
        config: 
            num_attention_heads: 8
            attention_probs_dropout_prob: 0.0
            hidden_dropout_prob: 0.0
            num_hidden_layers: 6
            hidden_size: 512
            vocab_size: 1428
            max_number_sent: 20
            intermediate_size: 1024
            vocab_path: /home/ptthang/gaze_sample/data_here/vocab.json
optimizer:
    name: AdamW
    args:
        lr: 1.0e-5
loss:
    name: CrossEntropyLoss
    args:
        # label_smoothing: 0.1
metric:
    - name: Bleu_1
    - name: Bleu_2
    - name: Bleu_3
    - name: Bleu_4
    - name: CIDEr
    - name: METEOR
    - name: ROUGE_L

scheduler: 
    name: WarmupLinearCosineAnnealing
    args:
        lr_warmup_epochs: 5
dataset: 
    train:
        name: GazeRealEval
        args:
            metadata: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata.json
            vocab: /home/ptthang/gaze_sample/data_here/vocab.json
            is_train: True 
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: False
                pin_memory: True
    val:
        name: GazeRealEval
        args:
            metadata: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val.json
            vocab: /home/ptthang/gaze_sample/data_here/vocab.json
            is_train: False 
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: False
                pin_memory: True

trainer: 
    nepochs: 500
    val_step: 1
    log_step: 1
    log_dir: runs
