id: label-smoothing-pe2-baseline6-subtest1-transformer-enc-thang-config-overfit
pretrained: null
seed: 420 # or 2210
amp: False
max_number_sent: 2

model:
    name: GazeBaseline6
    args:
        config: 
            num_attention_heads: 12
            attention_probs_dropout_prob: 0.1
            hidden_dropout_prob: 0.1
            num_hidden_layers: 3
            hidden_size: 768
            vocab_size: 1428
            max_number_sent: 20
            intermediate_size: 768
            bottleneck: 4
            vocab_path: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train_subtest1_vocab.json
optimizer:
    name: AdamW
    args:
        lr: 1.0e-4
loss:
    name: CrossEntropyLoss
    args:
        # label_smoothing: 0.1
metric:
    - name: Bleu_1
    - name: Bleu_2
    - name: Bleu_3
    - name: Bleu_4
    - name: CIDEr
    - name: METEOR
    - name: ROUGE_L
scheduler: 
    name: WarmupLinearCosineAnnealing
    args:
        lr_warmup_epochs: 20
dataset: 
    train:
        name: GazeReal_subtest1
        args:
            metadata: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train.json
            vocab: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train_subtest1_vocab.json
            subtest: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train_subtest1.json
            is_train: True 
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: True
                pin_memory: True
    val:
        name: GazeRealEval_subtest1
        args:
            metadata: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val.json
            vocab: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train_subtest1_vocab.json
            subtest: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_train_subtest1.json
            is_train: False 
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: False
                pin_memory: True

trainer: 
    nepochs: 200
    val_step: 1
    log_step: 1
    log_dir: runs
