id: sample-toying-baseline7
pretrained: null
seed: 420
amp: False
max_number_sent: 2
model:
    name: GazeBaseline7
    args:
        config: 
            num_attention_heads: 8
            attention_probs_dropout_prob: 0.1
            hidden_dropout_prob: 0.1
            num_hidden_layers: 1
            hidden_size: 784
            vocab_size: 833
            max_number_sent: 2
            intermediate_size: 784
            bottleneck: 4
            vocab_path: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val_subtest1_vocab.json
optimizer:
    name: AdamW
    args:
        lr: 1.0e-4
loss:
    name: CrossEntropyLoss
    args:
        # label_smoothing: 0.1
metric:
    - name: Bleu_1
    - name: Bleu_2
    - name: Bleu_3
    - name: Bleu_4
    - name: CIDEr
    - name: METEOR
    - name: ROUGE_L
scheduler: 
    name: WarmupLinearCosineAnnealing
    args:
        lr_warmup_epochs: 5
dataset: 
    train:
        name: GazeToy_subtest1
        args:
            metadata: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val.json
            vocab: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val_subtest1_vocab.json
            subtest: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val_subtest1.json
            is_train: False 
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: False
                pin_memory: True
    val:
        name: GazeToyEval_subtest1
        args:
            metadata: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val.json
            vocab: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val_subtest1_vocab.json
            subtest: /home/ptthang/gaze_sample/data_here/reflacx_new_metadata_val_subtest1.json
            is_train: False 
        loader:
            name: DataLoader
            args:
                batch_size: 1
                shuffle: False
                pin_memory: True

trainer: 
    nepochs: 100
    val_step: 1
    log_step: 1
    log_dir: runs
